"""empty message

Revision ID: 625571bebf71
Revises: 75630b7588ae
Create Date: 2023-11-29 17:05:36.339487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625571bebf71'
down_revision = '75630b7588ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
