"""empty message

Revision ID: cf40183981bb
Revises: 
Create Date: 2023-11-29 10:36:00.483339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf40183981bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form',
    sa.Column('firstname', sa.Integer(), nullable=False),
    sa.Column('lastname', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('firstname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form')
    # ### end Alembic commands ###
